export { authAPI } from './auth.js'
export { scopesAPI } from './scopes.js'
export { schemasAPI } from './schemas.js'
export { validationAPI } from './validation.js'
export { workflowAPI } from './workflow.js'
export { genesAPI } from './genes.js'
export { geneCatalogueAPI } from './geneCatalogue.js'
export { assignmentsAPI } from './assignments.js'
export { precurationsAPI } from './precurations.js'
export { curationsAPI } from './curations.js'
export { externalValidationAPI } from './externalValidation.js'
export { ontologyAPI } from './ontology.js'
export { publicationsAPI } from './publications.js'
export { default as apiClient } from './client.js'
