name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below to help us understand and fix the issue.

  - type: checkboxes
    id: preflight
    attributes:
      label: Preflight Checklist
      description: Please ensure you've completed the following steps
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I am using the latest version of Gene Curator
          required: true
        - label: I have checked the documentation
          required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which part of the application is affected?
      options:
        - Frontend (UI/UX)
        - Backend (API)
        - Database
        - Authentication
        - Curation Workflow
        - Schema Management
        - User Management
        - Other
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Where did the bug occur?
      options:
        - Development (local)
        - Docker (dev)
        - Hybrid (DB in Docker, API/Frontend local)
        - Production
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: |
        When I try to..., the application...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead, ...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: |
        If applicable, paste any error messages or logs. You can check:
        - Browser console (F12 → Console)
        - Backend logs (terminal running API)
        - Log Viewer in app (Ctrl+L / Cmd+L)
      render: shell
      placeholder: |
        Error: ...
        Stack trace: ...

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the problem. Drag and drop images here.

  - type: input
    id: version
    attributes:
      label: Gene Curator Version
      description: Check `make version` or footer in the UI
      placeholder: v2.0.0

  - type: input
    id: browser
    attributes:
      label: Browser (if frontend issue)
      description: Include version
      placeholder: Chrome 120, Firefox 121, Safari 17

  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: Ubuntu 22.04, macOS 14, Windows 11

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (Application unusable)
        - High (Major feature broken)
        - Medium (Feature partially broken)
        - Low (Minor issue, workaround available)
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I am willing to submit a pull request to fix this bug
