name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your idea.

  - type: checkboxes
    id: preflight
    attributes:
      label: Preflight Checklist
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have checked the roadmap (docs/ISSUE_ROADMAP.md)
          required: true
        - label: This feature aligns with Gene Curator's schema-agnostic design
          required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area does this feature belong to?
      options:
        - Core Curation Workflow
        - Dynamic Forms & Validation
        - External API Integration
        - Search & Discovery
        - Data Integrity & Management
        - Performance & Scalability
        - User Experience & Documentation
        - Production & Operations
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Describe the pain point or use case.
      placeholder: |
        As a [role], I want to [action] so that [benefit].

        Currently, when I try to..., I face the challenge of...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe how you envision this feature working
      placeholder: |
        The feature would work by...

        Users would interact with it by...

        The system would respond by...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: |
        Alternative 1: ...
        Alternative 2: ...

        Why the proposed solution is better: ...

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: How will we know when this feature is complete?
      placeholder: |
        - [ ] Users can do X
        - [ ] System validates Y
        - [ ] Feature works in Z scenario
        - [ ] Documentation updated
        - [ ] Tests added
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (Blocking current work)
        - High (Would significantly improve workflow)
        - Medium (Nice to have, would improve UX)
        - Low (Minor enhancement)
    validations:
      required: true

  - type: dropdown
    id: milestone
    attributes:
      label: Suggested Milestone
      description: When should this feature be considered?
      options:
        - v0.3.0 (Curation Readiness)
        - v0.4.0 (Performance & UX)
        - v0.5.0 (Generalization)
        - Future (Post v1.0)
        - Not sure

  - type: textarea
    id: impact
    attributes:
      label: Impact Assessment
      description: |
        Who would benefit from this feature? How many users? What workflows?
      placeholder: |
        - Affects: [curators/reviewers/admins/all users]
        - Number of users impacted: [rough estimate]
        - Workflows affected: [precuration/curation/review/etc.]
        - Frequency of use: [daily/weekly/monthly]

  - type: textarea
    id: technical
    attributes:
      label: Technical Considerations
      description: |
        If you have technical knowledge, describe any implementation details,
        database changes, API modifications, or architectural considerations
      placeholder: |
        - Backend changes needed: ...
        - Frontend changes needed: ...
        - Database schema changes: ...
        - External dependencies: ...

  - type: textarea
    id: examples
    attributes:
      label: Examples or Mockups
      description: |
        Provide examples from other tools, mockups, or screenshots that illustrate
        your idea. Drag and drop images here.

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that would help us understand your request

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I am willing to implement this feature
        - label: I am willing to provide design/mockups
        - label: I am willing to help test this feature
